name: checkout-to-pr
author: lazmond3
description: 'Checkout to issue commented PRs branch'
inputs:
  keyword:
    description: 'このコメントをトリガーにして、アクションが発火する'
outputs:
  result:
    description: sha hash of the latest commit
    value: ${{ steps.get-pr.outputs.result }}
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v3
      id: get-pr
      with:
        script: |
          const request = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          }
          core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
          try {
            const result = await github.pulls.get(request)
            return result.data
          } catch (err) {
            core.setFailed(`Request failed with error ${err}`)
          }
    - uses: actions/checkout@v2
      with:
        repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
        ref: ${{ fromJSON(steps.get-pr.outputs.result).head.ref }} # or .head.ref for branch name
